declare -A COLOR

# Foreground color
COLOR[default_fg]="\e[39m"
COLOR[black_fg]="\e[30m"
COLOR[red_fg]="\e[31m"
COLOR[green_fg]="\e[32m"
COLOR[yellow_fg]="\e[33m"
COLOR[blue_fg]="\e[34m"
COLOR[magenta_fg]="\e[35m"
COLOR[cyan_fg]="\e[36m"
COLOR[gray_fg]="\e[90m"
COLOR[lightred_fg]="\e[91m"
COLOR[lightgreen_fg]="\e[92m"
COLOR[lightyellow_fg]="\e[93m"
COLOR[lightblue_fg]="\e[94m"
COLOR[lightmagenta_fg]="\e[95m"
COLOR[lightcyan_fg]="\e[96m"
COLOR[white_fg]="\e[97m"

# Background color
COLOR[default_bg]="\e[49m"
COLOR[black_bg]="\e[40m"
COLOR[red_bg]="\e[41m"
COLOR[green_bg]="\e[42m"
COLOR[yellow_bg]="\e[43m"
COLOR[blue_bg]="\e[44m"
COLOR[magenta_bg]="\e[45m"
COLOR[cyan_bg]="\e[46m"
COLOR[gray_bg]="\e[100m"
COLOR[lightred_bg]="\e[101m"
COLOR[lightgreen_bg]="\e[102m"
COLOR[lightyellow_bg]="\e[103m"
COLOR[lightblue_bg]="\e[104m"
COLOR[lightmagenta_bg]="\e[105m"
COLOR[lightcyan_bg]="\e[106m"
COLOR[lightgray_bg]="\e[107m"
COLO[white_bg]="\e[107m"
